In [1]:
#matrix of 6*6 all elements 64
np.full(6,6),64)



SyntaxError: unmatched ')' (3155209219.py, line 2)

In [13]:
import numpy as np
np.full((6,6),64)




array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [21]:
#linspace = linearly spaced elements
np.linspace(0,1,100)


array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [25]:
np.linspace(15,20,20)


array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [27]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\riyan\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\riyan\anaconda3\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initial

In [29]:
np.random.random((3,3))
#it will give random values between 0 to 1

array([[0.18833569, 0.38805239, 0.90082425],
       [0.60856034, 0.31855507, 0.60067646],
       [0.49374012, 0.52039712, 0.88931852]])

In [31]:
np.random.normal?

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int 

In [39]:
np.random.normal((0,1,10))
#values with mean 0 and std 1

array([-1.36099599,  2.42919806, 11.89001188])

In [41]:
np.random.normal(0,1,10)

array([ 1.21360415, -0.53749457,  2.01737952,  0.00480729,  0.22690838,
       -0.08921791, -0.83020478, -1.97108295,  1.48627534,  0.10281773])

In [43]:
np.random.normal(0,1,(2,2))

array([[ 0.17716841,  0.77523563],
       [ 0.78333462, -0.69571911]])

In [45]:
np.random.seed?

Docstring:
seed(seed=None)

Reseed the singleton RandomState instance.

Notes
-----
This is a convenience, legacy function that exists to support
older code that uses the singleton RandomState. Best practice
is to use a dedicated ``Generator`` instance rather than
the random variate generation methods exposed directly in
the random module.

See Also
--------
numpy.random.Generator
Type:      builtin_function_or_method

In [49]:
np.random.seed(10)
np.random.random(10)

#seed will fix our results 

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [51]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [53]:
np.random.randint(100,200,50)

array([136, 116, 111, 154, 188, 162, 133, 172, 178, 149, 151, 154, 177,
       169, 113, 125, 113, 192, 186, 130, 130, 189, 112, 165, 131, 157,
       136, 127, 118, 193, 177, 122, 123, 194, 111, 128, 174, 188, 109,
       115, 118, 180, 171, 188, 111, 117, 146, 107, 175, 128])

In [55]:
np.random.randint(1,20,50)

array([ 2,  1, 13,  6,  5,  8, 19, 13,  3,  9, 16, 14, 16,  7, 11, 12, 17,
       13,  1, 18, 16, 13,  9, 11, 14, 12,  2, 19, 14,  9, 10,  6,  1, 19,
        4, 17, 19, 17, 15, 16, 18, 19, 15, 17, 11, 18,  1, 18, 10, 17])

In [57]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [67]:
arr=np.random.randint(0,100,20)


In [69]:
arr

array([93, 84, 48, 62, 42, 34, 40, 46, 32, 94, 86, 58, 69, 45, 18, 50, 44,
        1, 63, 77])

In [71]:
arr.ndim
#to check number of dimesion


1

In [73]:
arr.size

20

In [75]:
arr=np.random.randint(0,100,(2,2))

In [77]:
arr


array([[18, 27],
       [83, 37]])

In [79]:
arr.shape

(2, 2)

In [81]:
arr.dtype

dtype('int32')

In [83]:
arr.size

4

In [ ]:
#array indexing

In [85]:
arr1= np.random.randint(0,40,10)

In [87]:
arr1

array([ 7, 24, 39, 15,  6,  9,  0,  4, 14,  4])

In [89]:
arr1[4]

6

In [91]:
arr1[:9]

array([ 7, 24, 39, 15,  6,  9,  0,  4, 14])

In [95]:
arr1[6:]

array([ 0,  4, 14,  4])

In [97]:
arr1[4:7]

array([6, 9, 0])

In [99]:
#replacing a value
arr[1]

array([83, 37])

In [101]:
arr1[1]

24

In [111]:
arr1[1]=21

In [113]:
arr1

array([ 7, 21, 39, 15,  6,  9,  0,  4, 14,  4])

Assignment

In [115]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [117]:
np.full((1,1),6)

array([[6]])

In [119]:
np.full((2,2),8)

array([[8, 8],
       [8, 8]])

In [121]:
arr3=np.full(1,1),5

In [123]:
arr4=np.full(2,2),5

In [125]:
arr5=np.full((3,3),5)

In [127]:
arr3

(array([1]), 5)

In [129]:
arr4

(array([2, 2]), 5)

In [131]:
arr5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [133]:
arr5.dtype

dtype('int32')

In [135]:
arr5.size

9

In [139]:
arr5.shape

(3, 3)

In [143]:
arr6=np.full((1,12),0)

In [145]:
arr6

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [147]:
arr6.size

12

In [153]:
arr1=np.random.randint(10,100,(4,4))

In [155]:
arr1

array([[88, 89, 31, 79],
       [58, 70, 68, 23],
       [13, 41, 86, 97],
       [27, 39, 79, 60]])

In [157]:
4+arr1

array([[ 92,  93,  35,  83],
       [ 62,  74,  72,  27],
       [ 17,  45,  90, 101],
       [ 31,  43,  83,  64]])

In [ ]:
arr1[2:6:2]
