In [5]:
import numpy as np

arr=np.random.randint(20,100,20)

In [7]:
arr

array([97, 26, 56, 80, 85, 92, 85, 95, 76, 49, 83, 64, 94, 98, 62, 90, 24,
       43, 55, 79])

In [9]:
#2d array
array=np.full((2,2),5)

In [11]:
array

array([[5, 5],
       [5, 5]])

In [13]:
a1=np.random.randint(0,18,(4,4))

In [15]:
a1

array([[ 4, 15,  7, 14],
       [12, 14, 13, 12],
       [ 3,  3, 11,  8],
       [ 2,  6, 16, 14]])

In [17]:
a1[0,1:4]
#row ,column no.+1

array([15,  7, 14])

In [19]:
a1[0,1]
#row no.,column no.

15

In [21]:
a1[2,1]

3

In [23]:
a1[0:3,1]


array([15, 14,  3])

In [25]:
a1[0:2,1]

array([15, 14])

# 

In [29]:
a1[0:3,3]

array([14, 12,  8])

In [41]:
a1[0:3,0:3]

array([[ 4, 15,  7],
       [12, 14, 13],
       [ 3,  3, 11]])

In [43]:
a1[2:4,3:5]

array([[ 8],
       [14]])

In [45]:
a1[2:5,2:5]

array([[11,  8],
       [16, 14]])

In [47]:
a1[::,::]

array([[ 4, 15,  7, 14],
       [12, 14, 13, 12],
       [ 3,  3, 11,  8],
       [ 2,  6, 16, 14]])

In [49]:
a1[::-1,::]

array([[ 2,  6, 16, 14],
       [ 3,  3, 11,  8],
       [12, 14, 13, 12],
       [ 4, 15,  7, 14]])

In [32]:
a1[::-1,::-1]

NameError: name 'a1' is not defined

In [28]:
import numpy as np

In [ ]:
shallowcopy
a1=np.random.randint(0,18,(4,4))

In [38]:
a1

array([[ 7,  8, 10, 13],
       [15,  3, 12,  8],
       [15,  5,  0, 16],
       [ 9, 16, 12,  6]])

In [40]:
a1[1:3,1:3]

array([[ 3, 12],
       [ 5,  0]])

In [42]:
sa=a1[1:3,1:3]


In [44]:
sa

array([[ 3, 12],
       [ 5,  0]])

In [48]:
sa[1,1]=10

In [50]:
sa

array([[ 3, 12],
       [ 5, 10]])

In [52]:
a1

array([[ 7,  8, 10, 13],
       [15,  3, 12,  8],
       [15,  5, 10, 16],
       [ 9, 16, 12,  6]])

In [56]:
a1[1,1]=13

In [58]:
a1

array([[ 7,  8, 10, 13],
       [15, 13, 12,  8],
       [15,  5, 10, 16],
       [ 9, 16, 12,  6]])

Deepcopy

In [60]:
a1

array([[ 7,  8, 10, 13],
       [15, 13, 12,  8],
       [15,  5, 10, 16],
       [ 9, 16, 12,  6]])

In [62]:
a1[:2,:2]

array([[ 7,  8],
       [15, 13]])

In [68]:
da=a1[:2,:2].copy()


In [70]:
da

array([[ 7,  8],
       [15, 13]])

In [76]:
a1[0,0]=11


In [78]:
a1

array([[11,  8, 10, 13],
       [15, 13, 12,  8],
       [15,  5, 10, 16],
       [ 9, 16, 12,  6]])

In [80]:
da

array([[ 7,  8],
       [15, 13]])

In [82]:
da[1,1]=18

In [84]:
da

array([[ 7,  8],
       [15, 18]])

In [86]:
a1

array([[11,  8, 10, 13],
       [15, 13, 12,  8],
       [15,  5, 10, 16],
       [ 9, 16, 12,  6]])

In [88]:
a=np.arange(1,5)

In [90]:
a

array([1, 2, 3, 4])

In [102]:
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [116]:
a2=a.reshape(2,2)


In [118]:
a2

array([[1, 2],
       [3, 4]])

In [122]:
a2.reshape(1,4)

array([[1, 2, 3, 4]])

In [128]:
a2.ravel()


array([1, 2, 3, 4])

In [130]:
a1.ravel()

array([11,  8, 10, 13, 15, 13, 12,  8, 15,  5, 10, 16,  9, 16, 12,  6])

In [132]:
a1.flatten()

array([11,  8, 10, 13, 15, 13, 12,  8, 15,  5, 10, 16,  9, 16, 12,  6])

In [11]:
import numpy as np

In [15]:
a1=np.random.randint(0,18,(4,4))

In [21]:
a1

array([[ 6,  8,  6,  7],
       [15, 15,  7,  9],
       [16,  7, 16,  2],
       [ 0, 15, 17, 16]])

concatenation of array or joining of 2 arrays

In [23]:
a1[:2,:2]

array([[ 6,  8],
       [15, 15]])

In [25]:
sa=a1[:2,:2]

In [28]:
sa

array([[ 6,  8],
       [15, 15]])

In [42]:
a1[2:3,2:3]

array([[16]])

In [ ]:
#concation in row axis=0
#concatination in colunms asix=1

In [44]:
a2=a1

In [46]:
a2

array([[ 6,  8,  6,  7],
       [15, 15,  7,  9],
       [16,  7, 16,  2],
       [ 0, 15, 17, 16]])

In [48]:
np.concatenate([a1,a2])
#row concate-no.of column equal

array([[ 6,  8,  6,  7],
       [15, 15,  7,  9],
       [16,  7, 16,  2],
       [ 0, 15, 17, 16],
       [ 6,  8,  6,  7],
       [15, 15,  7,  9],
       [16,  7, 16,  2],
       [ 0, 15, 17, 16]])

In [50]:
np.concatenate([a1,a2],axis=1)
#column-no.of row should be equal

array([[ 6,  8,  6,  7,  6,  8,  6,  7],
       [15, 15,  7,  9, 15, 15,  7,  9],
       [16,  7, 16,  2, 16,  7, 16,  2],
       [ 0, 15, 17, 16,  0, 15, 17, 16]])

Numpy assignment 1

In [1]:
import numpy as np


In [3]:
a1=np.zeros(10)


In [5]:
a1


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
a2=np.ones(10)


In [9]:
a2


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
a3=np.arange(10,51)

In [13]:
a3


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [15]:
a4=np.arange(10,51,2)

In [17]:
a4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
a5=np.arange(0,9).reshape(3,3)

In [21]:
a5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
a6=np.identity(3)


In [27]:
a6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
num=np.random.normal(0,1,1)

In [49]:
num

array([1.20349142])

In [51]:
num1=np.random.normal(0,1,25)


In [53]:
num1

array([ 1.04250886e+00,  6.18415752e-02,  1.78866941e-01,  2.48558704e+00,
        2.92770267e-01, -7.71477241e-01, -9.48381059e-01, -6.48574826e-01,
        1.88022704e-01,  3.54619781e-01, -1.94800774e-01, -5.94691877e-01,
       -2.17298952e-01,  1.99231441e-01, -4.14210413e-01, -2.26590862e-01,
        4.18926643e-01, -1.61932690e-01, -1.20219177e+00, -8.45613315e-01,
        7.97739178e-02,  1.67298151e+00,  1.06023746e+00, -2.02884702e-03,
       -4.49219202e-02])

In [55]:
mat1 = np.linspace(0.01, 1, 100).reshape(10, 10)

In [57]:
mat1

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [59]:
arr=np.linspace(0,1,20)

In [61]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [1]:
import numpy as np


In [3]:
mat=np.arange(1,26).reshape(5,5)

In [5]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [9]:
mat[3,4]

20

In [11]:
mat[:3,1]

array([ 2,  7, 12])

In [38]:
mat[4:,:]

array([[21, 22, 23, 24, 25]])

In [40]:
mat[3,:]

array([16, 17, 18, 19, 20])

In [44]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [57]:
s1=sum(mat)

In [59]:
s1

array([55, 60, 65, 70, 75])

In [61]:
s2=np.sum(mat)

In [63]:
s2

325

In [1]:
import numpy as np

In [3]:
mat=np.arange(1,26).reshape(5,5)

In [5]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
np.std(mat,axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [9]:
np.var(mat,axis=1)

array([2., 2., 2., 2., 2.])

In [11]:
np.max(mat,axis=1)

array([ 5, 10, 15, 20, 25])

In [13]:
np.min(mat,axis=1)

array([ 1,  6, 11, 16, 21])

Numpy exercise 2

In [15]:
ar=np.array([1,2,3])

In [17]:
a1=np.array([[1,2,3]])

In [19]:
a1

array([[1, 2, 3]])

In [21]:
a2=np.array([[[1,2,3]]])

In [23]:
a2.ndim

3

In [25]:
a1.dtype

dtype('int32')

In [27]:
a1.shape

(1, 3)

In [29]:
a2.shape

(1, 1, 3)

In [33]:
a2.ndim

3

In [35]:
a3=np.zeros(12)

In [37]:
a3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
a4= np.ones((2,2))

In [41]:
a4

array([[1., 1.],
       [1., 1.]])

In [45]:
mathmarks=np.random.randint(0,101,20)

In [47]:
mathmarks

array([ 57,  36,  18,  55,  82,  96,  72,  48,  30,   6,   1,  31,  51,
        30,  77,  79,   5,  67,  59, 100])

In [49]:
np.sort(mathmarks)

array([  1,   5,   6,  18,  30,  30,  31,  36,  48,  51,  55,  57,  59,
        67,  72,  77,  79,  82,  96, 100])

In [53]:
np.sort(mathmarks)[::-1]

array([100,  96,  82,  79,  77,  72,  67,  59,  57,  55,  51,  48,  36,
        31,  30,  30,  18,   6,   5,   1])

In [59]:
x=mathmarks[2:8].copy

In [61]:
x

<function ndarray.copy>

In [63]:
a4=np.identity(5)

In [77]:
a4.ravel

<function ndarray.ravel>

In [67]:
a4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
a4.ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [83]:
ar=np.random.randint(0,8,(3,3))

In [85]:
ar

array([[1, 4, 6],
       [6, 4, 5],
       [0, 1, 2]])

In [87]:
ar1=np.array([[1,2,3]])

In [93]:
arr=np.concatenate([ar,ar1])

In [95]:
np.hsplit(arr,1)

[array([[1, 4, 6],
        [6, 4, 5],
        [0, 1, 2],
        [1, 2, 3]])]

In [97]:
np.vsplit(arr,2)

[array([[1, 4, 6],
        [6, 4, 5]]),
 array([[0, 1, 2],
        [1, 2, 3]])]

In [99]:
a5=np.identity(4)

In [101]:
a5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
a5+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [107]:
a6=np.random.randint(0,26,(5,5))

In [109]:
a6

array([[21, 21, 10,  1, 13],
       [14, 21, 17, 13,  0],
       [17,  1, 11, 24,  1],
       [ 3,  1, 20,  1, 20],
       [ 4,  5, 23, 13, 24]])

In [111]:
np.min(a6,axis=0)

array([ 3,  1, 10,  1,  0])

In [114]:
np.max(a6,axis=0)

array([21, 21, 23, 24, 24])

In [116]:
np.var(a6,axis=0)

array([50.96, 85.76, 25.36, 75.04, 94.64])

In [118]:
np.std(a6,axis=0)

array([7.13862732, 9.26066952, 5.03587132, 8.66256313, 9.72830921])

In [120]:
ar2=np.arange(100,151)

In [122]:
ar2

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [130]:
 ar2[::-1]

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [136]:
ar3=np.random.randint(0,25,(5,5))

In [138]:
ar3

array([[ 8, 18,  9,  1, 13],
       [19, 24, 12, 15, 22],
       [12, 16, 19,  7,  4],
       [ 0, 21,  5,  2, 10],
       [ 0, 12,  3, 21,  9]])

In [140]:
ar4=np.ones(100).reshape(10,10)

In [143]:
ar4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [145]:
ar4[1:9,1:9]=0

In [147]:
ar4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [161]:
ar5=np.zeros((8,8))

In [173]:
ar5[1::2,::2]=1


In [177]:
ar5[::2,1::2]=1

In [179]:
ar5

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [183]:
ar6=np.random.randint(0,8,(3,3))

In [185]:
ar7=np.random.randint(0,8,(3,3))


In [187]:
ar6+ar7

array([[ 5,  7,  5],
       [ 3,  7,  7],
       [10, 12,  8]])

In [189]:
ar6*ar7

array([[ 0, 10,  6],
       [ 2,  0,  0],
       [24, 35,  7]])

In [191]:
ar6-ar7

array([[ 5,  3, -1],
       [-1,  7, -7],
       [ 2,  2, -6]])

lecture continuation

In [65]:
x=np.array([1,2,3])

In [67]:
x

array([1, 2, 3])

In [77]:
y=np.array([4,5,6])

In [79]:
y

array([4, 5, 6])

In [81]:
np.vstack((x,y))
#row wise

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
np.hstack((x,y))
#column wise

array([1, 2, 3, 4, 5, 6])

In [85]:
np.hstack((x,[4]))

array([1, 2, 3, 4])

In [ ]:
#spilting the array
np.split
np.vsplit
np.hsplit
np.dsplit  , depth split

In [91]:
np.split(x,3)


[array([1]), array([2]), array([3])]

In [95]:
np.hsplit(x,3)

[array([1]), array([2]), array([3])]

In [103]:
z=np.array([1,2,3,4,5])

In [105]:
z

array([1, 2, 3, 4, 5])

In [107]:
np.split(z,[2,3])
#[:2],[2,3],[3:]

[array([1, 2]), array([3]), array([4, 5])]

In [109]:
np.split(z,[1,4])

[array([1]), array([2, 3, 4]), array([5])]

In [113]:
np.hsplit(z,5)

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [ ]:
universal function
#sum
mean
sd
variance
absolute

In [115]:
np.abs(-5)
#remove negative sign


5

In [ ]:
#aggregation

In [117]:
np.sum(z)

15

In [119]:
np.min(z)

1

In [121]:
np.max(z)

5

In [123]:
np.argmin(z)
#gives index of min & max

0

In [125]:
np.var(z)

2.0

In [127]:
np.std(z)

1.4142135623730951

In [129]:
np.product(z)

120

In [131]:
np.mean(z)

3.0

In [133]:
np.median(z)

3.0

In [139]:
np.percentile(z,2)


1.08

pandas

In [1]:
import numpy as np

In [3]:
import pandas as pd

In [7]:
productId= [1,2,3,4,5]

In [15]:
productname = ["a","b","c","d","e"]

In [19]:
productPrice = [100,20,320,466,78]

In [43]:
df=pd.DataFrame(productId,productname)

In [35]:
df

0
a  1
b  2
c  3
d  4
e  5

In [49]:
data = {'productId': [1,2,3,4,5], 'productname' : ["a","b","c","d","e"], 'productPrice' : [100,20,320,466,78]}

In [51]:
df1=pd.DataFrame(data)

In [53]:
df1

productId productname  productPrice
0          1           a           100
1          2           b            20
2          3           c           320
3          4           d           466
4          5           e            78

In [61]:
dict_list = df1.to_dict('records')

In [63]:
dict_list

[{'productId': 1, 'productname': 'a', 'productPrice': 100},
 {'productId': 2, 'productname': 'b', 'productPrice': 20},
 {'productId': 3, 'productname': 'c', 'productPrice': 320},
 {'productId': 4, 'productname': 'd', 'productPrice': 466},
 {'productId': 5, 'productname': 'e', 'productPrice': 78}]

In [75]:
df2=pd.DataFrame.from_dict(dict_list)

In [67]:
df2

productId productname  productPrice
0          1           a           100
1          2           b            20
2          3           c           320
3          4           d           466
4          5           e            78

In [2]:
import numpy as np
import pandas as pd

In [4]:
a=[17,10,15,3]


In [6]:
arr=np.array(a)

In [8]:
arr

array([17, 10, 15,  3])

# 

In [10]:
arr +4


array([21, 14, 19,  7])

In [12]:
arr


array([17, 10, 15,  3])

In [48]:
a2=np.zeros((10),dtype='i')

In [46]:
a2.dtype

dtype('int32')

In [52]:
a3=np.ones((3,7),dtype='f')

In [54]:
a3

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [56]:
a3[::]=17.15

In [58]:
a3

array([[17.15, 17.15, 17.15, 17.15, 17.15, 17.15, 17.15],
       [17.15, 17.15, 17.15, 17.15, 17.15, 17.15, 17.15],
       [17.15, 17.15, 17.15, 17.15, 17.15, 17.15, 17.15]], dtype=float32)

#### 

In [74]:
a4=np.linspace(0,14,3)

In [72]:
a4

array([ 0, 14,  3])

In [76]:
a5=np.linspace(0,15,3)

In [78]:
a5

array([ 0. ,  7.5, 15. ])

In [110]:
a6 = np.random.random((3,2))

In [112]:
a6

array([[0.31250447, 0.52131891],
       [0.39881444, 0.99096579],
       [0.2743759 , 0.29998888]])

In [136]:
a7=np.random.normal(4,4)

In [138]:
a7

7.356188335751705

PANDAS

In [3]:
import numpy as np
import pandas as pd

In [5]:
s=(1,2,3,4,5)

In [11]:
df=pd.DataFrame(s)

In [13]:
rng=np.random.RandomState(42)

In [17]:
ser=pd.Series(rng.randint(0,10,4))

In [19]:
ser

0    6
1    3
2    7
3    4
dtype: int32

In [21]:
df=pd.DataFrame(rng.randint(0,10,(3,4)),columns=['A','B','C','D,'])


In [23]:
df

A  B  C  D,
0  6  9  2   6
1  7  4  3   7
2  7  2  5   4

In [25]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [27]:
np.sin(df*np.pi/4)

A             B         C            D,
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [29]:
area=pd.Series({'Uttar Pradesh':243286,'Maharashtra':307713,'Bihar':104988},name='Area')

In [33]:
Pop=pd.Series({'West Bengal':54615521,'Maharashtra':12555465,'Bihar':26555422},name='Pop')

In [35]:
Population_density=Pop/area

In [37]:
Population_density

Bihar            252.937688
Maharashtra       40.802517
Uttar Pradesh           NaN
West Bengal             NaN
dtype: float64

In [53]:
A=pd.Series([2,4,6], index=[0,1,2])

In [55]:
B=pd.Series([1,3,5], index=[1,2,3])

In [57]:
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [65]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [67]:
A=pd.DataFrame(rng.randint(0,15,(2,2)),columns=list('AB'))

In [77]:
A

A   B
0   1   7
1  11  13

In [69]:
B=pd.DataFrame(rng.randint(0,10,(3,3)),columns=list('BAC'))

In [79]:
B

B  A  C
0  5  1  4
1  0  9  5
2  8  0  9

In [71]:
A+B

A     B   C
0   2.0  12.0 NaN
1  20.0  13.0 NaN
2   NaN   NaN NaN

In [73]:
fill = A.stack().mean()

In [75]:
A.add(B,fill_value=fill)

A     B     C
0   2.0  12.0  12.0
1  20.0  13.0  13.0
2   8.0  16.0  17.0

In [81]:
A=np.random.randint(10,size=(3,4))

In [83]:
A

array([[5, 7, 3, 8],
       [1, 1, 2, 5],
       [0, 1, 8, 1]])

In [85]:
A-A[0]

array([[ 0,  0,  0,  0],
       [-4, -6, -1, -3],
       [-5, -6,  5, -7]])

In [89]:
df=pd.DataFrame(A,columns=list('QRST'))

In [91]:
df-df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -4 -6 -1 -3
2 -5 -6  5 -7

In [93]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -2  0 -4  1
1  0  0  1  4
2 -1  0  7  0

In [95]:
halfrow=df.iloc[0,::2]

In [97]:
halfrow

Q    5
S    3
Name: 0, dtype: int32

In [99]:
df-halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -4.0 NaN -1.0 NaN
2 -5.0 NaN  5.0 NaN

In [39]:
Pop1=pd.Series({'Uttar Pradesh':54615521,'Maharashtra':12555465,'Bihar':26555422},name='Pop')

In [41]:
Population_density

Bihar            252.937688
Maharashtra       40.802517
Uttar Pradesh           NaN
West Bengal             NaN
dtype: float64

In [43]:
Population_density=Pop1/area

In [45]:
Population_density

Uttar Pradesh    224.491015
Maharashtra       40.802517
Bihar            252.937688
dtype: float64