In [5]:
import numpy as np

arr=np.random.randint(20,100,20)

In [7]:
arr

array([97, 26, 56, 80, 85, 92, 85, 95, 76, 49, 83, 64, 94, 98, 62, 90, 24,
       43, 55, 79])

In [9]:
#2d array
array=np.full((2,2),5)

In [11]:
array

array([[5, 5],
       [5, 5]])

In [13]:
a1=np.random.randint(0,18,(4,4))

In [15]:
a1

array([[ 4, 15,  7, 14],
       [12, 14, 13, 12],
       [ 3,  3, 11,  8],
       [ 2,  6, 16, 14]])

In [17]:
a1[0,1:4]
#row ,column no.+1

array([15,  7, 14])

In [19]:
a1[0,1]
#row no.,column no.

15

In [21]:
a1[2,1]

3

In [23]:
a1[0:3,1]


array([15, 14,  3])

In [25]:
a1[0:2,1]

array([15, 14])

# 

In [29]:
a1[0:3,3]

array([14, 12,  8])

In [41]:
a1[0:3,0:3]

array([[ 4, 15,  7],
       [12, 14, 13],
       [ 3,  3, 11]])

In [43]:
a1[2:4,3:5]

array([[ 8],
       [14]])

In [45]:
a1[2:5,2:5]

array([[11,  8],
       [16, 14]])

In [47]:
a1[::,::]

array([[ 4, 15,  7, 14],
       [12, 14, 13, 12],
       [ 3,  3, 11,  8],
       [ 2,  6, 16, 14]])

In [49]:
a1[::-1,::]

array([[ 2,  6, 16, 14],
       [ 3,  3, 11,  8],
       [12, 14, 13, 12],
       [ 4, 15,  7, 14]])

In [32]:
a1[::-1,::-1]

NameError: name 'a1' is not defined

In [28]:
import numpy as np

In [ ]:
shallowcopy
a1=np.random.randint(0,18,(4,4))

In [38]:
a1

array([[ 7,  8, 10, 13],
       [15,  3, 12,  8],
       [15,  5,  0, 16],
       [ 9, 16, 12,  6]])

In [40]:
a1[1:3,1:3]

array([[ 3, 12],
       [ 5,  0]])

In [42]:
sa=a1[1:3,1:3]


In [44]:
sa

array([[ 3, 12],
       [ 5,  0]])

In [48]:
sa[1,1]=10

In [50]:
sa

array([[ 3, 12],
       [ 5, 10]])

In [52]:
a1

array([[ 7,  8, 10, 13],
       [15,  3, 12,  8],
       [15,  5, 10, 16],
       [ 9, 16, 12,  6]])

In [56]:
a1[1,1]=13

In [58]:
a1

array([[ 7,  8, 10, 13],
       [15, 13, 12,  8],
       [15,  5, 10, 16],
       [ 9, 16, 12,  6]])

Deepcopy

In [60]:
a1

array([[ 7,  8, 10, 13],
       [15, 13, 12,  8],
       [15,  5, 10, 16],
       [ 9, 16, 12,  6]])

In [62]:
a1[:2,:2]

array([[ 7,  8],
       [15, 13]])

In [68]:
da=a1[:2,:2].copy()


In [70]:
da

array([[ 7,  8],
       [15, 13]])

In [76]:
a1[0,0]=11


In [78]:
a1

array([[11,  8, 10, 13],
       [15, 13, 12,  8],
       [15,  5, 10, 16],
       [ 9, 16, 12,  6]])

In [80]:
da

array([[ 7,  8],
       [15, 13]])

In [82]:
da[1,1]=18

In [84]:
da

array([[ 7,  8],
       [15, 18]])

In [86]:
a1

array([[11,  8, 10, 13],
       [15, 13, 12,  8],
       [15,  5, 10, 16],
       [ 9, 16, 12,  6]])

In [88]:
a=np.arange(1,5)

In [90]:
a

array([1, 2, 3, 4])

In [102]:
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [116]:
a2=a.reshape(2,2)


In [118]:
a2

array([[1, 2],
       [3, 4]])

In [122]:
a2.reshape(1,4)

array([[1, 2, 3, 4]])

In [128]:
a2.ravel()


array([1, 2, 3, 4])

In [130]:
a1.ravel()

array([11,  8, 10, 13, 15, 13, 12,  8, 15,  5, 10, 16,  9, 16, 12,  6])

In [132]:
a1.flatten()

array([11,  8, 10, 13, 15, 13, 12,  8, 15,  5, 10, 16,  9, 16, 12,  6])

In [11]:
import numpy as np

In [15]:
a1=np.random.randint(0,18,(4,4))

In [21]:
a1

array([[ 6,  8,  6,  7],
       [15, 15,  7,  9],
       [16,  7, 16,  2],
       [ 0, 15, 17, 16]])

concatenation of array or joining of 2 arrays

In [23]:
a1[:2,:2]

array([[ 6,  8],
       [15, 15]])

In [25]:
sa=a1[:2,:2]

In [28]:
sa

array([[ 6,  8],
       [15, 15]])

In [42]:
a1[2:3,2:3]

array([[16]])

In [ ]:
#concation in row axis=0
#concatination in colunms asix=1

In [44]:
a2=a1

In [46]:
a2

array([[ 6,  8,  6,  7],
       [15, 15,  7,  9],
       [16,  7, 16,  2],
       [ 0, 15, 17, 16]])

In [48]:
np.concatenate([a1,a2])
#row concate-no.of column equal

array([[ 6,  8,  6,  7],
       [15, 15,  7,  9],
       [16,  7, 16,  2],
       [ 0, 15, 17, 16],
       [ 6,  8,  6,  7],
       [15, 15,  7,  9],
       [16,  7, 16,  2],
       [ 0, 15, 17, 16]])

In [50]:
np.concatenate([a1,a2],axis=1)
#column-no.of row should be equal

array([[ 6,  8,  6,  7,  6,  8,  6,  7],
       [15, 15,  7,  9, 15, 15,  7,  9],
       [16,  7, 16,  2, 16,  7, 16,  2],
       [ 0, 15, 17, 16,  0, 15, 17, 16]])

Numpy assignment 1

In [1]:
import numpy as np


In [3]:
a1=np.zeros(10)


In [5]:
a1


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
a2=np.ones(10)


In [9]:
a2


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
a3=np.arange(10,51)

In [13]:
a3


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [15]:
a4=np.arange(10,51,2)

In [17]:
a4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
a5=np.arange(0,9).reshape(3,3)

In [21]:
a5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
a6=np.identity(3)


In [27]:
a6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
num=np.random.normal(0,1,1)

In [49]:
num

array([1.20349142])

In [51]:
num1=np.random.normal(0,1,25)


In [53]:
num1

array([ 1.04250886e+00,  6.18415752e-02,  1.78866941e-01,  2.48558704e+00,
        2.92770267e-01, -7.71477241e-01, -9.48381059e-01, -6.48574826e-01,
        1.88022704e-01,  3.54619781e-01, -1.94800774e-01, -5.94691877e-01,
       -2.17298952e-01,  1.99231441e-01, -4.14210413e-01, -2.26590862e-01,
        4.18926643e-01, -1.61932690e-01, -1.20219177e+00, -8.45613315e-01,
        7.97739178e-02,  1.67298151e+00,  1.06023746e+00, -2.02884702e-03,
       -4.49219202e-02])

In [55]:
mat1 = np.linspace(0.01, 1, 100).reshape(10, 10)

In [57]:
mat1

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [59]:
arr=np.linspace(0,1,20)

In [61]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

lecture continuation

In [65]:
x=np.array([1,2,3])

In [67]:
x

array([1, 2, 3])

In [77]:
y=np.array([4,5,6])

In [79]:
y

array([4, 5, 6])

In [81]:
np.vstack((x,y))
#row wise

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
np.hstack((x,y))
#column wise

array([1, 2, 3, 4, 5, 6])

In [85]:
np.hstack((x,[4]))

array([1, 2, 3, 4])

In [ ]:
#spilting the array
np.split
np.vsplit
np.hsplit
np.dsplit  , depth split

In [91]:
np.split(x,3)


[array([1]), array([2]), array([3])]

In [95]:
np.hsplit(x,3)

[array([1]), array([2]), array([3])]

In [103]:
z=np.array([1,2,3,4,5])

In [105]:
z

array([1, 2, 3, 4, 5])

In [107]:
np.split(z,[2,3])
#[:2],[2,3],[3:]

[array([1, 2]), array([3]), array([4, 5])]

In [109]:
np.split(z,[1,4])

[array([1]), array([2, 3, 4]), array([5])]

In [113]:
np.hsplit(z,5)

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [ ]:
universal function
#sum
mean
sd
variance
absolute

In [115]:
np.abs(-5)
#remove negative sign


5

In [ ]:
#aggregation

In [117]:
np.sum(z)

15

In [119]:
np.min(z)

1

In [121]:
np.max(z)

5

In [123]:
np.argmin(z)
#gives index of min & max

0

In [125]:
np.var(z)

2.0

In [127]:
np.std(z)

1.4142135623730951

In [129]:
np.product(z)

120

In [131]:
np.mean(z)

3.0

In [133]:
np.median(z)

3.0

In [139]:
np.percentile(z,2)


1.08